app/common/view.c, app/common/view.h, app/common/view_internal.h, app/common/view_s.c, app/common/view_x.c, include/app_mode.h, include/zxversion.h, src/app_mode.c
=> Crowdloan UI

include/zxmacros_ledger.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/2mdbew9)
=> moving includes

include/zxversion.h, scripts/template.sh
:link: [zboto Link](https://app.clickup.com/t/2mrqea3)
=> fix installer for nanosplus 1.0.3 firmware version

.github/workflows/main.yml, include/zxversion.h, scripts/get_version.sh
:link: [zboto Link](https://app.clickup.com/t/2nfme5h)
=> improve CI

include/zxversion.h, scripts/template.sh
:link: [zboto Link](https://app.clickup.com/t/2hjdza4)
=> fix installer for nanos

.github/workflows/main.yml, include/zxversion.h, src/base58.c
:link: [zboto Link](https://app.clickup.com/t/31papy2)
=> fix: memzero base58 encoding

dockerized_build.mk, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/31pd092)
=> fix: set dev_caS2 targetId properly

include/zxformat.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/34hwk55)
=> Add print hex method

app/common/view.c, app/common/view.h, app/common/view_internal.h, app/common/view_s.c, app/common/view_x.c, include/zxversion.h, scripts/getSize.py
:link: [zboto Link](https://app.clickup.com/t/377vp29)
=> Add init menu

include/zxformat.h, include/zxversion.h
Add new methods:
- toUppercase (char)
- toLowercase (char)
- array_to_uppercase (array)
- array_to_lowercase (array)
- array_to_hexstr_uppercase (converts an array of numbers to hexstring using uppercase letters)
=> Utils functions

app/common/app_main.c, app/common/app_main.h, app/ui/view.c, app/ui/view.h, app/ui/view_internal.h, app/ui/view_nano.c, app/ui/view_nano.h, app/ui/view_s.c, app/ui/view_x.c, include/zxversion.h, makefiles/Makefile.app_testing, makefiles/Makefile.c_app, makefiles/Makefile.devices, makefiles/Makefile.installer_script, makefiles/Makefile.platform, makefiles/Makefile.side_loading
Move general configuration from Makefile to ZXLib
Move app_main to ZXLib
Restructure UI files
:link: [zboto Link](https://app.clickup.com/t/39xfkaj)
=> Unifying configurations

include/zxformat.h, include/zxversion.h, tests/zxformat.cpp
:link: [zboto Link](https://app.clickup.com/t/86773zb3m)
=> Fix hex2str

include/zxversion.h, scripts/install_deps.sh
:link: [zboto Link](https://app.clickup.com/t/8677g3b2h)
=> fix: pin conan v1

dockerized_build.mk, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8677jpda9)
=> feat: update dockerized build to use new image

app/common/app_main.c, app/ui/view_nano.c, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861mgrnt5)
=> fix: use custom defined function for initialize

app/common/app_main.c, include/zxversion.h, makefiles/Makefile.platform
Update io_event() function with latest changes from Boilerplate app
Remove unnecessary includes for Ledger Stax
=> Updates for Stax

dockerized_build.mk, include/zxversion.h, scripts/getSize.py
:link: [zboto Link](https://app.clickup.com/t/863gbfq8u)
=> feat: add size<Device> to dockerized_build and improve script

app/ui/view_nano.c, app/ui/view_nano.h, app/ui/view_s.c, include/zxversion.h
Move specific NanoS function to `view_s` and marked variable as unused
=> Fix warnings

include/zxmacros.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/863gevukr)
=> feat: add UNUSED macro if it's not defined by sdk

app/ui/view_stax.c, dockerized_build.mk, include/zxversion.h
Include transition animation
Modify several texts 
Add mechanism to set a custom text to describe transaction
:link: [zboto Link](https://app.clickup.com/t/861mmxrj3)
=> Normalize texts for Stax

dockerized_build.mk, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8677uxbkn)
=> feat: bump container

app/ui/view_stax.c, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861mp1n22)
=> Remove shortcut Stax

app/ui/view.c, app/ui/view.h, app/ui/view_internal.h, app/ui/view_nano.c, app/ui/view_s.c, app/ui/view_stax.c, app/ui/view_x.c, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8677wh59w)
=> fix: flag as const some strings

app/ui/view_stax.c, include/zxversion.h
Handle more than one items under address review menu
Allow to a custom message for review address menu
=> Improve address menu

app/ui/view_stax.c, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8677xcd1f)
=> fix: remove useless pointer

app/ui/view_stax.c, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861mqf2dm)
=> Show message Stax

include/zxversion.h, src/zxformat.c
:link: [zboto Link](https://app.clickup.com/t/8677xutmj)
=> Add checks

app/ui/view.h, app/ui/view_internal.h, app/ui/view_nano.c, app/ui/view_s.c, app/ui/view_stax.c, app/ui/view_x.c, include/zxversion.h
Transform custom error into menu window, requiring error acknowledge from the user.
:link: [zboto Link](https://app.clickup.com/t/8677zan2a)
=> Feat fix custom error

dockerized_build.mk, include/zxformat.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861mv10e4)
=> Extra checks

include/zxformat.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/863guugfz)
=> Improvements

app/ui/view_stax.c, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861my3u64)
=> Fix error message UI

dockerized_build.mk, include/zxmacros_ledger.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861n09hhh)
=> macros to handle CX errors

include/zxmacros_ledger.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861n179gr)
=> fix: rename err variable

include/zxmacros_ledger.h, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/861n1a9pp)
=> fix: missing var rename

app/ui/view.h, app/ui/view_inspect_s.c, app/ui/view_inspect_x.c, app/ui/view_internal.h, app/ui/view_nano_inspect.c, app/ui/view_nano_inspect.h, app/ui/view_s.c, app/ui/view_x.c, include/zxversion.h
Add menu to UI to inspect elements when array, maps or vectors must be displayed
=> Inspect menu

app/ui/view_x.c, include/zxversion.h
Disable inspect menu callback when is feature is not built
=> Disable callback

app/common/app_main.c, dockerized_build.mk, include/zxversion.h
Remove superfluous RAM reset in swap mode
Put sign status and return to Exchange in the app itself
:link: [zboto Link](https://app.clickup.com/t/8692tuf5f)
=> Improve Swap mode

app/ui/view.c, app/ui/view.h, app/ui/view_internal.h, app/ui/view_nano.c, app/ui/view_x.c, dockerized_build.mk, include/zxversion.h
Add menu for Nano devices to display a message. This does not activate/deactivate any feature from the device.
There is a similar function but it only allows 1 page messages without explicit confirmation from the user.
⚠️ DO NOT MERGE THIS YET
**S**
**S+/X**
:link: [zboto Link](https://app.clickup.com/t/8693b2k12)
=> Review message menu

app/ui/view_nano.c, include/zxversion.h
Remove `addr.h` from zxlib since that file is part of the application and it's not used at all in zxlib
=> Minor fixes

dockerized_build.mk, include/zxversion.h
Update docker image to build the app for the following SDK version:
```
ENV NANOS_SDK=/opt/nanos-secure-sdk
RUN git clone --branch v2.1.0-19 --depth 1 "$GIT_SERVER/nanos-secure-sdk.git" "$NANOS_SDK"
RUN git -C "$LEDGER_SECURE_SDK" worktree add "$NANOX_SDK" v5.11.1
RUN git -C "$LEDGER_SECURE_SDK" worktree add "$NANOSP_SDK" v5.11.1
RUN git -C "$LEDGER_SECURE_SDK" worktree add "$STAX_SDK" v15.4.0
RUN git -C "$LEDGER_SECURE_SDK" worktree add "$FLEX_SDK" v18.3.0
```
=> Update docker image

.github/workflows/main.yml, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8694haft4)
=> migrate to checkout@4 to avoid node warnings

dockerized_build.mk, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8694uhncv)
=> additional makefile helpers

app/ui/view_internal.h, app/ui/view_nbgl.c, dockerized_build.mk, include/zxmacros.h, include/zxmacros_ledger.h, include/zxmacros_x64.h, include/zxversion.h, makefiles/Makefile.devices, makefiles/Makefile.platform, src/app_mode.c, src/zxmacros.c
Update Stax to API_LEVEL 21
Support for Flex device
Stax and Flex devices will be built be default when running `make` command
:link: [zboto Link](https://app.clickup.com/t/86954au3q)
=> Support for Flex device

app/ui/view_nbgl.c, dockerized_build.mk, include/zxversion.h, makefiles/Makefile.devices
Set by default if it's not set an `APP_STACK_MIN_SIZE`
Adapt Stax and Flex UI to use the latest useCases from SDK
Minor UI adjustment
=> Flex fixes

app/ui/view_internal.h, include/zxversion.h
Fix the screen on Stax when displaying 6 items
:link: [zboto Link](https://app.clickup.com/t/8695etm9y)
=> Fix stax screen

app/ui/view.h, app/ui/view_internal.h, app/ui/view_nano.c, app/ui/view_x.c, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8696db9e9)
=> Improve blindsign

app/ui/view_s.c, include/zxversion.h
Restore functions that were present in v30.1.1.
Mark unused parameters as unused.
=> Unused params nanos

app/ui/view.c, app/ui/view.h, app/ui/view_internal.h, app/ui/view_nbgl.c, app/ui/view_s.c, app/ui/view_x.c, include/zxversion.h
Added a static screen with a loading icon to be used when the parser or another process takes a long time to compute the data
:link: [zboto Link](https://app.clickup.com/t/8697rtmpw)
=> Processing screen

include/zxversion.h, makefiles/Makefile.platform
Reverted QR in address review for Stax and Flex devices
=> Fix QR in show address 

include/zxversion.h, makefiles/Makefile.platform
:link: [zboto Link](https://app.clickup.com/t/8697udzft)
=> Revert QR flag 

app/ui/view.h, app/ui/view_nano.c, app/ui/view_s.c, app/ui/view_x.c, include/zxversion.h
- Added review type REVIEW_GROUP_TXN
- Added mechanism to modify title and subtitle in review screen
=> Review Group feature on nano devices

include/zxversion.h, makefiles/Makefile.devices, makefiles/Makefile.platform
Removed some defines
Moved version setting to the app's makefile
Moved APP_SOURCE_PATH to app
Improved permission settings
Moved icon set to app
:link: [zboto Link](https://app.clickup.com/t/8697ybxp2)
=> Improve make flow

dockerized_build.mk, include/zxversion.h
:link: [zboto Link](https://app.clickup.com/t/8699dwryt)
=> Add update_snapshots target to dockerized_build.mk

dockerized_build.mk, include/zxversion.h
Added coverage reports commands 
:link: [zboto Link](https://app.clickup.com/t/8699jp48w)
=> Fuzz coverage
